/**
 * Generate Gravity UI brand theme CSS via @gravity-ui/uikit-themer.
 *
 * Default Gravity brand accent is yellow (#FFBE5C). Nebius-style violet replaces it:
 * themer rebuilds --g-color-private-brand-*, then we remap semantic brand tokens
 * (base-brand, selection, links, …) onto that palette. Yellow stays available for warning.
 *
 * Usage: npx tsx scripts/generate-brand-theme.ts
 */
import {mkdirSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {
  DEFAULT_THEME,
  generateCSS,
  updateBaseColor,
  type GravityTheme,
} from '@gravity-ui/uikit-themer';

/** Solid accent sampled from Nebius console (≈ #5048E0…#5B4CE8). */
const BRAND_LIGHT = '#5B4CE8';
/** Slightly brighter for dark surfaces. */
const BRAND_DARK = '#8B7CF7';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '../src/styles/brand-theme.css');

type ThemeVariant = 'light' | 'dark';

function withUtilityRef(
  theme: GravityTheme,
  token: string,
  refs: Record<ThemeVariant, string>,
): GravityTheme {
  return {
    ...theme,
    utilityColors: {
      ...theme.utilityColors,
      [token]: {
        light: {ref: refs.light},
        dark: {ref: refs.dark},
      },
    },
  };
}

function buildTheme(): GravityTheme {
  // Rebuild private brand scale from the base hex (do not edit private-* by hand).
  let theme = updateBaseColor({
    theme: DEFAULT_THEME,
    colorToken: 'brand',
    value: {light: BRAND_LIGHT, dark: BRAND_DARK},
  });

  // Default Gravity maps brand semantics → private.yellow.*. Point them at brand.
  const remap: Record<string, Record<ThemeVariant, string>> = {
    'base-brand': {
      light: 'private.brand.550-solid',
      dark: 'private.brand.550-solid',
    },
    'base-brand-hover': {
      light: 'private.brand.600-solid',
      dark: 'private.brand.650-solid',
    },
    'base-selection': {
      light: 'private.brand.100',
      dark: 'private.brand.150',
    },
    'base-selection-hover': {
      light: 'private.brand.200',
      dark: 'private.brand.200',
    },
    'line-brand': {
      light: 'private.brand.550-solid',
      dark: 'private.brand.550-solid',
    },
    'text-brand': {
      light: 'private.brand.550-solid',
      dark: 'private.brand.550-solid',
    },
    'text-brand-heavy': {
      light: 'private.brand.700-solid',
      dark: 'private.brand.700-solid',
    },
    'text-link': {
      light: 'private.brand.550-solid',
      dark: 'private.brand.550-solid',
    },
    'text-link-hover': {
      light: 'private.brand.700-solid',
      dark: 'private.brand.700-solid',
    },
  };

  for (const [token, refs] of Object.entries(remap)) {
    theme = withUtilityRef(theme, token, refs);
  }

  // Yellow brand used dark glyphs on the chip; purple needs light contrast (Nebius-style).
  theme = withUtilityRef(theme, 'text-brand-contrast', {
    light: 'utility.text-light-primary',
    dark: 'utility.text-light-primary',
  });

  return theme;
}

const css = generateCSS({theme: buildTheme(), ignoreDefaultValues: true});
const banner = `/* AUTO-GENERATED by scripts/generate-brand-theme.ts — do not edit by hand.
 * Brand: Nebius-like violet ${BRAND_LIGHT} (light) / ${BRAND_DARK} (dark).
 * Regenerate: npm run theme:brand
 */
`;

mkdirSync(dirname(OUT), {recursive: true});
writeFileSync(OUT, `${banner}\n${css.trim()}\n`);
console.log(`Wrote ${OUT}`);
